# Project information
site_name: 60portunities
site_description: Documentação do Horacio
site_author: Horacio Vasconcellos
site_url: https://60portunities.github.io/devops/

repo_name: 60portunities/devops
repo_url: https://github.com/60portunities/devops

copyright:  >
   Copyright &copy; 2023 Documentação
   <a href="#__consent">Change cookie settings</a>
extra_css:
  - styles/app-theme.css
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - styles/tablesort.css
  - styles/bbts-themas.css
extra_javascript:
  - javascripts/tables.js
  - javascripts/tablesort.js
validation:
  omitted_files: ignore
  absolute_links: ignore  # Or 'relative_to_docs' - new in MkDocs 1.6
  unrecognized_links: ignore
  anchors: ignore
theme:
  icon:
    repo: fontawesome/brands/git-alt 
  logo: img/logo.jpeg
  custom_dir: theme
  highlightjs: true
  features:
    - announce.dismiss
    - commit
    - content.code.annotation
    - content.code.copy
    - search.highlight
    - search.share
    - search.suggest
    - version
  favicon: img/favicon.ico
  name: material
  icon:
    logo: img/favicon.ico
  palette:
   # Palette toggle for light mode
   - media: "(prefers-color-scheme: light)"
     scheme: default
     primary: light blue
     accent: indigo
     toggle:
       icon: material/weather-night
       name: Azul da cor do mar
   # Palette toggle for dark mode
   - media: "(prefers-color-scheme: dark)"
     scheme: default 
     primary: indigo
     accent: light blue
     toggle:
       icon: material/weather-sunny
       name: Rock and Roll 
plugins:
  - git-committers:
      repository: 60portunities/devops
      branch: gh-pages
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true
# - blog:
#      blog_dir: .
  - search
  - autorefs
#  - mkdocstrings:
#      handlers:
#        python:
#          options:
#            docstring_style: sphinx
#  - monorepo
  - include-markdown:
      #encoding: ascii
      preserve_includer_indent: false
      dedent: false
      trailing_newlines: true
      comments: true
      rewrite_relative_urls: true
      heading_offset: 0
      start: <!--start-->
      end: <!--end-->
  - table-reader
  - glightbox:
      touchNavigation: true
      loop: true
      height: auto
      width: 80%
  - swagger-ui-tag:
       background: White
  - render_swagger
  - mike
  - mermaid2:
      version: 10.0.2
  - minify:
      minify_html: true
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - attr_list
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - admonition
  - abbr
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  analytics:
    provider: google
    property: G-horacio
  consent:
    title: Consentimento
    description: >- 
       Utilizamos cookies para reconhecer as suas repetidas visitas e preferências, bem como
       para medir a eficácia da nossa documentação e se os usuários
       encontre o que eles estão procurando. Com o seu consentimento, você está nos ajudando a
       melhorar nossa documentação.
  version:
    provider: mike
    default: latest
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/horaciovasconcellos 
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/horaciovasconcellos
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Horacio_Junior
      name: Horacio.Vasconcellos on Twitter
    - icon: fontawesome/brands/mastodon
      name: Horaci.Vasconcellos on Mastodon
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/squidfunk/mkdocs-material
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/77678117787
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hor%C3%A1cio-correa-t-de-vasconcellos-j%C3%BAnior-b7788467/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/horacio.vasconcellos/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/horacio.vasconcellos
    - icon: fontawesome/brands/medium
      link: https://www.bbts.com.br
    - icon: fontawesome/brands/pied-piper-alt
      link: https://www.bbts.com.br
    - icon: fontawesome/brands/product-hunt
      link: https://www.producthunt.com/@horacio_vasconcellos
    - icon: fontawesome/brands/slack
      link: https://gitlab.com/horaciovasconcellos
    - icon: fontawesome/brands/discord
      link: http://intranet.bbts.com.br
    - icon: fontawesome/solid/paper-plane
      mailto: horacio.vasconcellos@gmail.com
#not_in_nav: |

nav:
   - 'Inicio'                                        :
      - 'Changelog'                                  : 'CHANGELOG.md'
      - 'Contribuições'                              : 'CONTRIBUTING.md'
      - 'Codigo de Conduta'                          : 'CODE_OF_CONDUCT.md'
   - 'Propósitos'                                    :
      - 'Conceitos'                                  : 'recipe_60pportunities_conceitos.md'
   - 'Registro'                                      :
      - 'Registrando um Domínio'                     : 'recipe_60pportunities_conf_registrobr_dominio.md'
   - 'Github'                                        : 
      - 'Conta no Github'                            : 'recipe_60pportunities_conf_github_conta.md'
      - 'Configurando Pages'                         : 'recipe_60pportunities_conf_github_pages.md'
      - 'Publicando Pages no Domínio'                : 'recipe_60pportunities_conf_github_dominio_pages.md'
   - 'Documentação as Code'                          : 
      - 'Documentação'                               : 'recipe_60pportunities_conf_documentacao.md'
      - 'Usando o MkDocs'                            : 'recipe_60pportunities_conf_mkdocs.md'
      - 'Publicando MkDocs no Github'                : 'recipe_60pportunities_conf_mkdocs_publicacao.md'
   - 'Dados Empresariais'                            :
      - 'Segregation of Duties'                      : 'recipe_60pportunities_conf_sod.md'
      - 'Mascaramento de dados'                      : 'recipe_60pportunities_conf_data_mask.md'
      - 'Dados Mestres/Referência'                   : 'recipe_60pportunities_conf_data_master.md'
      - 'Central de Cadastro'                        : 'recipe_60pportunities_conf_central_cadastro.md'
   - 'Desenvolvedor'                                 :
      - 'Visual Code'                                : 'recipe_60pportunities_conf_vscode.md'
      - 'Data-Driven'                                : 'recipe_60pportunities_conf_datadriven.md'
      - 'Mensagens'                                  : 'recipe_60pportunities_conf_mensagens.md'
      - 'Versionamento'                              :
         - 'Versionamento'                           : 'recipe_60pportunities_conf_git.md'
         - 'Estratégia de Branch'                    : 'recipe_60pportunities_conf_branch.md'
      - 'Observabilidade e Logs'                     : 'recipe_60pportunities_conf_logs.md'
      - 'Docker'                                     : 'recipe_60pportunities_conf_docker.md'
      - 'Jenkins'                                    : 'recipe_60pportunities_conf_jenkins.md'

   - 'Projetos'                                      :
      - 'Formulário de Projetos'                     : 'recipe_60pportunities_metodologia.md'
      - 'Configuração Plataformas'                   :
         - 'Github'                                  : 'recipe_60pportunities_conf_github.md'
         - 'Azure-Devops'                            : 'recipe_60pportunities_conf_azuredevops.md'
      - 'Métricas'                                   :
         - 'Métricas Internas'                       : 'recipe_60pportunities_conf_metricas.md'
   - 'Estudos/Aprendizado'                           : 
      - 'Arquitetura'                                : 'recipe_60pportunities_arquitetonicos.md'
      - 'Application Program Interface'              : 'recipe_60pportunities_conf_api.md'
      - 'Inteligencia Artificial'                    : 'recipe_60pportunities_conf_inteligencia_artificial.md'
   - 'Simulados ou Provas'                           :
      - 'Github Foundation'                          : 'estudo_60pportunities_certificacao_github.md'
   - 'Dicionário'                                    :
      - 'Termos'                                     : 'recipe_60pportunities_tesauro.md'
   - 'Links Úteis para o Aprendizado'                :
      - 'Inteligência Artificial'                    : 'recipe_links_inteligencia_artificial.md'
      - 'Biblioteca Virtual'                         : 'recipe_links_biblioteca_virtual.md'
